import { apartment } from "../data/apartment.js";
import { isoDate } from "../data/availability.js";
import { sectionHeading } from "./shared.js";
export function InquiryForm(t) {
  const f = t.inquiry,
    c = apartment.contact;
  const input = (name, label, type = "text", optional = false) =>
    `<label>${label}${optional ? ` <span class="optional">(${f.optional})</span>` : ""}<input name="${name}" type="${type}" ${optional ? "" : "required"} ${type === "date" ? `min="${isoDate()}"` : 'maxlength="200"'} ${name === "name" ? 'autocomplete="name"' : name === "email" ? 'autocomplete="email"' : name === "phone" ? 'autocomplete="tel"' : ""}></label>`;
  return `<section class="inquiry-section" id="inquiry"><div>${sectionHeading(f.eyebrow, f.title)}<p>${f.intro}</p><div class="inquiry-signature"><span class="brand-word">The Princess</span><span>Kroogblöcke 2 · Hamburg</span></div></div><form id="inquiry-form"><div class="form-grid">${input("name", f.name)}${input("email", f.email, "email")}${input("phone", f.phone, "tel", true)}<label>${f.occupants}<input type="number" name="occupants" min="1" step="1" ${apartment.policies.occupants ? `max="${apartment.policies.occupants}"` : ""} required value="1"></label>${input("start", f.start, "date")}${input("end", f.end, "date")}<label class="full">${f.reason}<select name="reason" required><option value="">${f.select}</option>${f.reasons.map((x, i) => `<option value="${i}">${x}</option>`).join("")}</select></label><div class="full">${input("occupation", f.occupation, "text", true)}</div><label class="full">${f.message} <span class="optional">(${f.optional})</span><textarea name="message" rows="3" maxlength="2000"></textarea></label></div><div class="honeypot" aria-hidden="true"><label>${f.honeypot}<input name="website" tabindex="-1" autocomplete="off"></label></div><label class="consent-check"><input type="checkbox" name="privacy" required><span>${f.privacy} <a href="#datenschutz">${f.privacyLink}</a></span></label><p class="small-copy">${c.endpoint ? "" : c.email ? f.mailNote : f.noRecipient}</p><p id="form-error" role="alert" tabindex="-1" hidden></p><button type="submit" class="button">${c.endpoint ? f.submit : c.email ? f.mail : f.download}<span aria-hidden="true">↗</span></button><p id="form-status" role="status" aria-live="polite"></p></form></section>`;
}
